# Generated by Django 3.2 on 2021-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(default='branding', max_length=10),
        ),
    ]
