# Generated by Django 3.2 on 2021-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fraud_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='identity',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
