# Generated by Django 3.2.3 on 2021-06-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=250)),
                ('similar', models.CharField(max_length=250)),
                ('score', models.CharField(default='0', max_length=20)),
                ('updated', models.CharField(max_length=20)),
            ],
        ),
    ]
