# Generated by Django 3.2 on 2021-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10)),
                ('updated', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
