# Generated by Django 3.2 on 2021-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_report_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('identity', models.CharField(default='0000000000', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='identity',
        ),
    ]
